import type { Question } from "./types";

export const ALL_QUESTIONS: Question[] = [
  // ─── same_denominator (15) ────────────────────────────────────────────────
  {
    id: "sd-01",
    type: "same_denominator",
    left: { numerator: 3, denominator: 8 },
    right: { numerator: 5, denominator: 8 },
    correctSide: "right",
    difficulty: 1,
    strategy: "When denominators match, the larger numerator wins — the pieces are identical in size.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "5/8 is larger: both fractions have equal-sized pieces (eighths), and 5 pieces is more than 3.",
  },
  {
    id: "sd-02",
    type: "same_denominator",
    left: { numerator: 4, denominator: 5 },
    right: { numerator: 2, denominator: 5 },
    correctSide: "left",
    difficulty: 1,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "4/5 is larger: both use fifths, and 4 fifths is more than 2 fifths.",
  },
  {
    id: "sd-03",
    type: "same_denominator",
    left: { numerator: 1, denominator: 6 },
    right: { numerator: 5, denominator: 6 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "5/6 is larger: the pieces are the same size, and 5 of them is more than 1.",
  },
  {
    id: "sd-04",
    type: "same_denominator",
    left: { numerator: 7, denominator: 10 },
    right: { numerator: 3, denominator: 10 },
    correctSide: "left",
    difficulty: 1,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "7/10 is larger: both use tenths, and 7 is greater than 3.",
  },
  {
    id: "sd-05",
    type: "same_denominator",
    left: { numerator: 1, denominator: 4 },
    right: { numerator: 3, denominator: 4 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "3/4 is larger: both use fourths, and 3 pieces is more than 1.",
  },
  {
    id: "sd-06",
    type: "same_denominator",
    left: { numerator: 5, denominator: 9 },
    right: { numerator: 7, denominator: 9 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "7/9 is larger: both are ninths, and 7 > 5.",
  },
  {
    id: "sd-07",
    type: "same_denominator",
    left: { numerator: 6, denominator: 7 },
    right: { numerator: 4, denominator: 7 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "6/7 is larger: both use sevenths, and 6 > 4.",
  },
  {
    id: "sd-08",
    type: "same_denominator",
    left: { numerator: 8, denominator: 11 },
    right: { numerator: 6, denominator: 11 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "8/11 is larger: both are elevenths, and 8 > 6.",
  },
  {
    id: "sd-09",
    type: "same_denominator",
    left: { numerator: 3, denominator: 12 },
    right: { numerator: 9, denominator: 12 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "9/12 is larger: both use twelfths, and 9 > 3.",
  },
  {
    id: "sd-10",
    type: "same_denominator",
    left: { numerator: 7, denominator: 15 },
    right: { numerator: 11, denominator: 15 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "11/15 is larger: both use fifteenths, and 11 > 7.",
  },
  {
    id: "sd-11",
    type: "same_denominator",
    left: { numerator: 13, denominator: 20 },
    right: { numerator: 11, denominator: 20 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "13/20 is larger: both use twentieths, and 13 > 11.",
  },
  {
    id: "sd-12",
    type: "same_denominator",
    left: { numerator: 9, denominator: 16 },
    right: { numerator: 11, denominator: 16 },
    correctSide: "right",
    difficulty: 3,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "11/16 is larger: both use sixteenths, and 11 > 9.",
  },
  {
    id: "sd-13",
    type: "same_denominator",
    left: { numerator: 11, denominator: 24 },
    right: { numerator: 7, denominator: 24 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "11/24 is larger: both use twenty-fourths, and 11 > 7.",
  },
  {
    id: "sd-14",
    type: "same_denominator",
    left: { numerator: 17, denominator: 30 },
    right: { numerator: 13, denominator: 30 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "17/30 is larger: both use thirtieths, and 17 > 13.",
  },
  {
    id: "sd-15",
    type: "same_denominator",
    left: { numerator: 8, denominator: 13 },
    right: { numerator: 10, denominator: 13 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Same denominator — just compare the numerators.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "10/13 is larger: both use thirteenths, and 10 > 8.",
  },

  // ─── same_numerator (15) ──────────────────────────────────────────────────
  {
    id: "sn-01",
    type: "same_numerator",
    left: { numerator: 1, denominator: 3 },
    right: { numerator: 1, denominator: 5 },
    correctSide: "left",
    difficulty: 1,
    strategy: "Same numerator — the fraction with the smaller denominator has bigger pieces, so it's larger.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "1/3 is larger: thirds are bigger pieces than fifths — a whole cut into 3 gives larger slices than one cut into 5.",
  },
  {
    id: "sn-02",
    type: "same_numerator",
    left: { numerator: 1, denominator: 2 },
    right: { numerator: 1, denominator: 4 },
    correctSide: "left",
    difficulty: 1,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "1/2 is larger: halves are bigger than quarters — dividing into 2 gives larger pieces than dividing into 4.",
  },
  {
    id: "sn-03",
    type: "same_numerator",
    left: { numerator: 2, denominator: 3 },
    right: { numerator: 2, denominator: 7 },
    correctSide: "left",
    difficulty: 1,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "2/3 is larger: thirds are much bigger than sevenths, so 2 thirds beats 2 sevenths.",
  },
  {
    id: "sn-04",
    type: "same_numerator",
    left: { numerator: 3, denominator: 4 },
    right: { numerator: 3, denominator: 8 },
    correctSide: "left",
    difficulty: 1,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "3/4 is larger: fourths are bigger pieces than eighths, so 3 fourths is more than 3 eighths.",
  },
  {
    id: "sn-05",
    type: "same_numerator",
    left: { numerator: 1, denominator: 6 },
    right: { numerator: 1, denominator: 3 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "1/3 is larger: thirds are bigger pieces than sixths — the smaller the denominator, the larger each piece.",
  },
  {
    id: "sn-06",
    type: "same_numerator",
    left: { numerator: 5, denominator: 9 },
    right: { numerator: 5, denominator: 6 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "5/6 is larger: sixths are bigger pieces than ninths, so 5 sixths is more than 5 ninths.",
  },
  {
    id: "sn-07",
    type: "same_numerator",
    left: { numerator: 3, denominator: 10 },
    right: { numerator: 3, denominator: 5 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "3/5 is larger: fifths are bigger than tenths, so 3 fifths is twice as much as 3 tenths.",
  },
  {
    id: "sn-08",
    type: "same_numerator",
    left: { numerator: 4, denominator: 5 },
    right: { numerator: 4, denominator: 7 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "4/5 is larger: fifths are bigger pieces than sevenths, so 4 fifths beats 4 sevenths.",
  },
  {
    id: "sn-09",
    type: "same_numerator",
    left: { numerator: 2, denominator: 5 },
    right: { numerator: 2, denominator: 9 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "2/5 is larger: fifths are bigger than ninths, so 2/5 = 0.4 while 2/9 ≈ 0.22.",
  },
  {
    id: "sn-10",
    type: "same_numerator",
    left: { numerator: 7, denominator: 8 },
    right: { numerator: 7, denominator: 12 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "7/8 is larger: eighths are bigger pieces than twelfths, so 7 eighths is more than 7 twelfths.",
  },
  {
    id: "sn-11",
    type: "same_numerator",
    left: { numerator: 5, denominator: 9 },
    right: { numerator: 5, denominator: 11 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Same numerator — the fraction with the smaller denominator is larger.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "5/9 is larger: ninths are bigger than elevenths, so 5/9 ≈ 0.56 while 5/11 ≈ 0.45.",
  },
  {
    id: "sn-12",
    type: "same_numerator",
    left: { numerator: 6, denominator: 11 },
    right: { numerator: 6, denominator: 13 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Same numerator — the fraction with the smaller denominator is larger.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "6/11 is larger: elevenths are bigger pieces than thirteenths — 6/11 ≈ 0.55 versus 6/13 ≈ 0.46.",
  },
  {
    id: "sn-13",
    type: "same_numerator",
    left: { numerator: 4, denominator: 9 },
    right: { numerator: 4, denominator: 15 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Same numerator — the fraction with the smaller denominator is larger.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "4/9 is larger: ninths are larger pieces than fifteenths, so 4/9 ≈ 0.44 beats 4/15 ≈ 0.27.",
  },
  {
    id: "sn-14",
    type: "same_numerator",
    left: { numerator: 3, denominator: 11 },
    right: { numerator: 3, denominator: 16 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Same numerator — the fraction with the smaller denominator is larger.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "3/11 is larger: elevenths are bigger pieces than sixteenths — 3/11 ≈ 0.27 versus 3/16 ≈ 0.19.",
  },
  {
    id: "sn-15",
    type: "same_numerator",
    left: { numerator: 8, denominator: 9 },
    right: { numerator: 8, denominator: 15 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Same numerator — the fraction with the smaller denominator is larger.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "8/9 is larger: ninths are bigger pieces than fifteenths, so 8/9 ≈ 0.89 while 8/15 ≈ 0.53.",
  },

  // ─── benchmark (15) ───────────────────────────────────────────────────────
  {
    id: "bm-01",
    type: "benchmark",
    left: { numerator: 3, denominator: 8 },
    right: { numerator: 5, denominator: 9 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Compare each to ½. One is above ½, one is below — the one above is larger.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "5/9 is larger: 3/8 = 0.375 is below ½, while 5/9 ≈ 0.56 is above ½.",
  },
  {
    id: "bm-02",
    type: "benchmark",
    left: { numerator: 1, denominator: 3 },
    right: { numerator: 4, denominator: 7 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Compare each to ½. One is above ½, one is below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "4/7 is larger: 1/3 ≈ 0.33 is well below ½, while 4/7 ≈ 0.57 is above ½.",
  },
  {
    id: "bm-03",
    type: "benchmark",
    left: { numerator: 5, denominator: 8 },
    right: { numerator: 3, denominator: 7 },
    correctSide: "left",
    difficulty: 1,
    strategy: "Compare each to ½. One is above ½, one is below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "5/8 is larger: 5/8 = 0.625 is above ½, while 3/7 ≈ 0.43 is below ½.",
  },
  {
    id: "bm-04",
    type: "benchmark",
    left: { numerator: 2, denominator: 5 },
    right: { numerator: 7, denominator: 12 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Compare each to ½. One is above ½, one is below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "7/12 is larger: 2/5 = 0.4 is below ½, while 7/12 ≈ 0.58 is above ½.",
  },
  {
    id: "bm-05",
    type: "benchmark",
    left: { numerator: 5, denominator: 11 },
    right: { numerator: 7, denominator: 12 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Compare each to ½. One is above, one is below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "7/12 is larger: 5/11 ≈ 0.45 is just below ½, while 7/12 ≈ 0.58 is above ½.",
  },
  {
    id: "bm-06",
    type: "benchmark",
    left: { numerator: 4, denominator: 9 },
    right: { numerator: 6, denominator: 11 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Compare each to ½. One is above, one is below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "6/11 is larger: 4/9 ≈ 0.44 is below ½, while 6/11 ≈ 0.55 is above ½.",
  },
  {
    id: "bm-07",
    type: "benchmark",
    left: { numerator: 7, denominator: 15 },
    right: { numerator: 9, denominator: 17 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Compare each to ½. One is above, one is below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "9/17 is larger: 7/15 ≈ 0.47 is just below ½, while 9/17 ≈ 0.53 is just above ½.",
  },
  {
    id: "bm-08",
    type: "benchmark",
    left: { numerator: 8, denominator: 15 },
    right: { numerator: 6, denominator: 13 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Compare each to ½. One is above, one is below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "8/15 is larger: 8/15 ≈ 0.53 is above ½, while 6/13 ≈ 0.46 is below ½.",
  },
  {
    id: "bm-09",
    type: "benchmark",
    left: { numerator: 4, denominator: 11 },
    right: { numerator: 7, denominator: 13 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Compare each to ½. One is clearly above, one is clearly below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "7/13 is larger: 4/11 ≈ 0.36 is well below ½, while 7/13 ≈ 0.54 is above ½.",
  },
  {
    id: "bm-10",
    type: "benchmark",
    left: { numerator: 7, denominator: 16 },
    right: { numerator: 9, denominator: 17 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Compare each to ½. One is above, one is below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "9/17 is larger: 7/16 = 0.4375 is below ½, while 9/17 ≈ 0.53 is above ½.",
  },
  {
    id: "bm-11",
    type: "benchmark",
    left: { numerator: 11, denominator: 21 },
    right: { numerator: 9, denominator: 19 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Check which side of ½ each fraction lands on.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "11/21 is larger: 11/21 ≈ 0.524 is just above ½, while 9/19 ≈ 0.474 is just below ½.",
  },
  {
    id: "bm-12",
    type: "benchmark",
    left: { numerator: 6, denominator: 11 },
    right: { numerator: 8, denominator: 17 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Check if each fraction is above or below ½.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "6/11 is larger: 6/11 ≈ 0.55 is above ½, while 8/17 ≈ 0.47 is below ½.",
  },
  {
    id: "bm-13",
    type: "benchmark",
    left: { numerator: 10, denominator: 19 },
    right: { numerator: 7, denominator: 15 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Check if each fraction is above or below ½.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "10/19 is larger: 10/19 ≈ 0.526 is just above ½, while 7/15 ≈ 0.467 is just below ½.",
  },
  {
    id: "bm-14",
    type: "benchmark",
    left: { numerator: 3, denominator: 8 },
    right: { numerator: 9, denominator: 16 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Compare each to ½. One is above ½, one is below.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "9/16 is larger: 3/8 = 0.375 is below ½, while 9/16 = 0.5625 is above ½.",
  },
  {
    id: "bm-15",
    type: "benchmark",
    left: { numerator: 7, denominator: 8 },
    right: { numerator: 9, denominator: 10 },
    correctSide: "right",
    difficulty: 3,
    strategy: "Both are close to 1 — check how far each is from a whole: 1−7/8 = 1/8, 1−9/10 = 1/10. Smaller gap means larger fraction.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "9/10 is larger: 9/10 = 0.9 versus 7/8 = 0.875. The fraction closer to 1 is larger.",
  },

  // ─── unlike_fractions (20) ────────────────────────────────────────────────
  {
    id: "uf-01",
    type: "unlike_fractions",
    left: { numerator: 1, denominator: 2 },
    right: { numerator: 2, denominator: 3 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Use ½ as a reference: 1/2 is exactly ½, and 2/3 ≈ 0.67 is above ½.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "2/3 is larger: 1/2 = 0.5 and 2/3 ≈ 0.67. Two-thirds takes up more of a whole.",
  },
  {
    id: "uf-02",
    type: "unlike_fractions",
    left: { numerator: 2, denominator: 3 },
    right: { numerator: 3, denominator: 4 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Convert to a common denominator: 2/3 = 8/12, 3/4 = 9/12. Compare numerators.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "3/4 is larger: 2/3 = 8/12 and 3/4 = 9/12 — 9 twelfths beats 8 twelfths.",
  },
  {
    id: "uf-03",
    type: "unlike_fractions",
    left: { numerator: 1, denominator: 3 },
    right: { numerator: 2, denominator: 5 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Cross-multiply to compare: 1×5 = 5, 3×2 = 6. Larger product indicates the larger fraction.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "2/5 is larger: 1/3 ≈ 0.33 and 2/5 = 0.4. Cross-multiply: 1×5 = 5 < 3×2 = 6.",
  },
  {
    id: "uf-04",
    type: "unlike_fractions",
    left: { numerator: 1, denominator: 4 },
    right: { numerator: 2, denominator: 9 },
    correctSide: "left",
    difficulty: 1,
    strategy: "Cross-multiply: 1×9 = 9, 4×2 = 8. Larger product wins.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "1/4 is larger: 1×9 = 9 > 4×2 = 8, so 1/4 > 2/9. (0.25 vs 0.22)",
  },
  {
    id: "uf-05",
    type: "unlike_fractions",
    left: { numerator: 3, denominator: 4 },
    right: { numerator: 4, denominator: 5 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Both are close to 1. Check what's missing: 1−3/4 = 1/4, 1−4/5 = 1/5. Smaller gap = larger fraction.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "4/5 is larger: 3/4 = 0.75 and 4/5 = 0.8. 4/5 is one-fifth from a whole; 3/4 is one-quarter from a whole.",
  },
  {
    id: "uf-06",
    type: "unlike_fractions",
    left: { numerator: 2, denominator: 5 },
    right: { numerator: 3, denominator: 7 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Cross-multiply: 2×7 = 14, 5×3 = 15. Larger product wins.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "3/7 is larger: 2×7 = 14 < 5×3 = 15, so 2/5 < 3/7. (0.4 vs 0.43)",
  },
  {
    id: "uf-07",
    type: "unlike_fractions",
    left: { numerator: 7, denominator: 10 },
    right: { numerator: 3, denominator: 4 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Convert to a common denominator: 7/10 = 14/20, 3/4 = 15/20.",
    misconceptionTrap: "numerator_only_comparison",
    explanation: "3/4 is larger: 7/10 = 0.7 and 3/4 = 0.75. Don't be misled by the larger numerator — 3/4 has bigger pieces.",
  },
  {
    id: "uf-08",
    type: "unlike_fractions",
    left: { numerator: 5, denominator: 7 },
    right: { numerator: 4, denominator: 5 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Compare distance from 1: 1−5/7 = 2/7 ≈ 0.29, 1−4/5 = 1/5 = 0.2. Smaller gap = larger.",
    misconceptionTrap: "numerator_only_comparison",
    explanation: "4/5 is larger: 5/7 ≈ 0.71 and 4/5 = 0.8. Though 5/7 has a larger numerator, 4/5 is closer to 1.",
  },
  {
    id: "uf-09",
    type: "unlike_fractions",
    left: { numerator: 3, denominator: 8 },
    right: { numerator: 2, denominator: 7 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Cross-multiply: 3×7 = 21, 8×2 = 16. Larger product wins.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "3/8 is larger: 3×7 = 21 > 8×2 = 16. So 3/8 > 2/7. (0.375 vs 0.286)",
  },
  {
    id: "uf-10",
    type: "unlike_fractions",
    left: { numerator: 3, denominator: 5 },
    right: { numerator: 7, denominator: 12 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Convert to a common denominator: 3/5 = 36/60, 7/12 = 35/60.",
    misconceptionTrap: "numerator_only_comparison",
    explanation: "3/5 is larger: 3/5 = 0.6 and 7/12 ≈ 0.583. Though 7/12 has a bigger numerator, 3/5 is slightly more.",
  },
  {
    id: "uf-11",
    type: "unlike_fractions",
    left: { numerator: 3, denominator: 5 },
    right: { numerator: 5, denominator: 8 },
    correctSide: "right",
    difficulty: 3,
    strategy: "Cross-multiply: 3×8 = 24, 5×5 = 25. Larger product wins.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "5/8 is larger: 3×8 = 24 < 5×5 = 25, so 3/5 < 5/8. (0.6 vs 0.625)",
  },
  {
    id: "uf-12",
    type: "unlike_fractions",
    left: { numerator: 5, denominator: 6 },
    right: { numerator: 7, denominator: 8 },
    correctSide: "right",
    difficulty: 3,
    strategy: "Compare distance from 1: 1−5/6 = 1/6, 1−7/8 = 1/8. Smaller gap = larger fraction.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "7/8 is larger: 5/6 ≈ 0.833 and 7/8 = 0.875. 7/8 is one-eighth from a whole, 5/6 is one-sixth.",
  },
  {
    id: "uf-13",
    type: "unlike_fractions",
    left: { numerator: 4, denominator: 9 },
    right: { numerator: 5, denominator: 11 },
    correctSide: "right",
    difficulty: 3,
    strategy: "Cross-multiply: 4×11 = 44, 9×5 = 45. Larger product indicates the larger fraction.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "5/11 is larger: 4×11 = 44 < 9×5 = 45, so 4/9 < 5/11. These are very close (0.44 vs 0.45).",
  },
  {
    id: "uf-14",
    type: "unlike_fractions",
    left: { numerator: 5, denominator: 9 },
    right: { numerator: 4, denominator: 7 },
    correctSide: "right",
    difficulty: 3,
    strategy: "Cross-multiply: 5×7 = 35, 9×4 = 36. Larger product wins.",
    misconceptionTrap: "numerator_only_comparison",
    explanation: "4/7 is larger: 5×7 = 35 < 9×4 = 36, so 5/9 < 4/7. (0.556 vs 0.571)",
  },
  {
    id: "uf-15",
    type: "unlike_fractions",
    left: { numerator: 7, denominator: 12 },
    right: { numerator: 5, denominator: 9 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Cross-multiply: 7×9 = 63, 12×5 = 60. Larger product wins.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "7/12 is larger: 7×9 = 63 > 12×5 = 60, so 7/12 > 5/9. (0.583 vs 0.556)",
  },
  {
    id: "uf-16",
    type: "unlike_fractions",
    left: { numerator: 5, denominator: 8 },
    right: { numerator: 7, denominator: 11 },
    correctSide: "right",
    difficulty: 3,
    strategy: "Cross-multiply: 5×11 = 55, 8×7 = 56. Larger product wins.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "7/11 is larger: 5×11 = 55 < 8×7 = 56, so 5/8 < 7/11. (0.625 vs 0.636)",
  },
  {
    id: "uf-17",
    type: "unlike_fractions",
    left: { numerator: 2, denominator: 7 },
    right: { numerator: 3, denominator: 11 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Cross-multiply: 2×11 = 22, 7×3 = 21. Larger product wins.",
    misconceptionTrap: "numerator_only_comparison",
    explanation: "2/7 is larger: 2×11 = 22 > 7×3 = 21, so 2/7 > 3/11. (0.286 vs 0.273)",
  },
  {
    id: "uf-18",
    type: "unlike_fractions",
    left: { numerator: 9, denominator: 10 },
    right: { numerator: 8, denominator: 9 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Compare distance from 1: 1−9/10 = 1/10, 1−8/9 = 1/9. Smaller gap means larger fraction.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "9/10 is larger: 9/10 = 0.9 versus 8/9 ≈ 0.889. 9/10 is only one-tenth from a whole.",
  },
  {
    id: "uf-19",
    type: "unlike_fractions",
    left: { numerator: 6, denominator: 7 },
    right: { numerator: 5, denominator: 6 },
    correctSide: "left",
    difficulty: 3,
    strategy: "Compare distance from 1: 1−6/7 = 1/7, 1−5/6 = 1/6. Smaller gap = larger fraction.",
    misconceptionTrap: "equivalent_fraction_weakness",
    explanation: "6/7 is larger: 6/7 ≈ 0.857 versus 5/6 ≈ 0.833. 6/7 is one-seventh from a whole; 5/6 is one-sixth.",
  },
  {
    id: "uf-20",
    type: "unlike_fractions",
    left: { numerator: 4, denominator: 6 },
    right: { numerator: 5, denominator: 8 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Simplify if possible: 4/6 = 2/3. Then convert: 2/3 = 16/24, 5/8 = 15/24.",
    misconceptionTrap: "numerator_only_comparison",
    explanation: "4/6 is larger: 4/6 simplifies to 2/3 ≈ 0.667, which is more than 5/8 = 0.625.",
  },

  // ─── retry variants (6) ───────────────────────────────────────────────────
  {
    id: "rv-01",
    type: "same_numerator",
    left: { numerator: 5, denominator: 7 },
    right: { numerator: 5, denominator: 12 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Same numerator — the fraction with the smaller denominator is larger.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "5/7 is larger: sevenths are bigger pieces than twelfths, so 5/7 ≈ 0.71 beats 5/12 ≈ 0.42.",
    usage: "retry",
  },
  {
    id: "rv-02",
    type: "same_numerator",
    left: { numerator: 4, denominator: 6 },
    right: { numerator: 4, denominator: 9 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Same numerator — smaller denominator means bigger pieces.",
    misconceptionTrap: "bigger_denominator_means_bigger_fraction",
    explanation: "4/6 is larger: sixths are bigger than ninths, so 4/6 ≈ 0.67 versus 4/9 ≈ 0.44.",
    usage: "retry",
  },
  {
    id: "rv-03",
    type: "benchmark",
    left: { numerator: 3, denominator: 10 },
    right: { numerator: 7, denominator: 12 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Compare each to ½ — one is clearly below, one is clearly above.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "7/12 is larger: 3/10 = 0.3 is well below ½, while 7/12 ≈ 0.58 is above ½.",
    usage: "retry",
  },
  {
    id: "rv-04",
    type: "unlike_fractions",
    left: { numerator: 3, denominator: 4 },
    right: { numerator: 7, denominator: 10 },
    correctSide: "left",
    difficulty: 2,
    strategy: "Convert to a common denominator: 3/4 = 15/20, 7/10 = 14/20.",
    misconceptionTrap: "numerator_only_comparison",
    explanation: "3/4 is larger: 3/4 = 0.75 and 7/10 = 0.7. Even though 7 > 3, the piece sizes differ.",
    usage: "retry",
  },
  {
    id: "rv-05",
    type: "same_denominator",
    left: { numerator: 5, denominator: 12 },
    right: { numerator: 9, denominator: 12 },
    correctSide: "right",
    difficulty: 1,
    strategy: "Same denominator — compare the numerators directly.",
    misconceptionTrap: "careless_or_rushing",
    explanation: "9/12 is larger: both use twelfths, and 9 > 5.",
    usage: "retry",
  },
  {
    id: "rv-06",
    type: "benchmark",
    left: { numerator: 4, denominator: 9 },
    right: { numerator: 5, denominator: 8 },
    correctSide: "right",
    difficulty: 2,
    strategy: "Compare each to ½ — one is below, one is above.",
    misconceptionTrap: "weak_benchmark_reasoning",
    explanation: "5/8 is larger: 4/9 ≈ 0.44 is below ½, while 5/8 = 0.625 is above ½.",
    usage: "retry",
  },
];
